config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'drones#index'
  resources :drones, expect: [:index] do
    get 'request', to: 'drones#request'
  end

  resources :mypage, only: [:index] do
    get 'users/edit'
    patch 'users/update'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/drone.rb
class Drone < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  has_many :imgs, dependent: :destroy
  has_many :drone_features
  belongs_to :station
  belongs_to :maker, optional: true
  belongs_to_active_hash :size
  belongs_to_active_hash :weight
  belongs_to_active_hash :speed
  belongs_to_active_hash :load
  belongs_to_active_hash :space
  accepts_nested_attributes_for :imgs, allow_destroy: true

  enum status: {requestable: 0, in_transit: 1,in_preparation: 2 }

  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true
  validates :area, presence: true
  validates :status, presence: true
  validates :size_id, presence: true
  validates :weight_id, presence: true
  validates :load_id, presence: true
  validates :space_id, presence: true
end

app/models/drone_feature.rb
class DroneFeature < ApplicationRecord
end

app/models/feature.rb
class Feature < ActiveHash::Base
  self.data = [{id: 1, name: '冷蔵対応'}, {id: 2, name: '冷凍対応'}, {id: 3, name: '保温対応'}, {id: 4, name: '遮光対応'}]
end

app/models/img.rb
class Img < ApplicationRecord
  mount_uploader :src, ImageUploader
  belongs_to :drone, optional: true

  validates :src, presence: true
end

app/models/load.rb
class Load < ActiveHash::Base
  self.data = [
    {id: 1, name: '〜10kg'},
    {id: 2, name: '10kg〜50kg'},
    {id: 3, name: '50kg～100kg'},
    {id: 4, name: '〜100kg'}
  ]
end

app/models/maker.rb
class Maker < ApplicationRecord
  has_many :drones
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
end

app/models/size.rb
class Size < ActiveHash::Base
  self.data = [
    {id: 1, name: '小型（参：〜350mm）'},
    {id: 2, name: '中型（参：350mm～700mm）'},
    {id: 3, name: '大型（参：700mm～1400mm）'}
  ]
end

app/models/space.rb
class Space < ActiveHash::Base
  self.data = [
    {id: 1, name: '〜 0.5m×0.5m'},
    {id: 2, name: '～ 1m×1m'},
    {id: 3, name: '～ 2m×2m'}
  ]
end

app/models/speed.rb
class Speed < ActiveHash::Base
  self.data = [
    {id: 1, name: '〜50km/h'},
    {id: 2, name: '50km/h〜100km/h'},
    {id: 3, name: '100km/h～'},
  ]
end

app/models/station.rb
class Station < ApplicationRecord
  has_many :drones
  has_ancestry
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, :family_name, :first_name, :family_name_kana, :first_name_kana, :phone_number, presence: true
end

app/models/weight.rb
class Weight < ActiveHash::Base
  self.data = [
    {id: 1, name: '〜200g'},
    {id: 2, name: '200〜700g'},
    {id: 3, name: '700g～'},
  ]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth, if: :production?
  protect_from_forgery with: :exception
  before_action :basic_auth
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :family_name, :first_name, :family_name_kana, :first_name_kana, :phone_number])
  end

  private
  def production?
    Rails.env.production?
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end
end

app/controllers/drones_controller.rb
class DronesController < ApplicationController
  #before_action :set_drone, only: [:show]
  before_action :set_station, only: [:new]

  def index
    @drones = Drone.all
  end

  def show
  end

  def new
    @drone = Drone.new
    @drone.imgs.build
  end

  def create
    @drone = Drone.new(drone_params)
    maker = Maker.new

    if @drone.save
      redirect_to root_path
    else
      flash.now[:alert] = "登録に失敗しました"
    end
  end

  private
  def set_station
    @station_parent_array = Station.where(ancestry: nil)
  end

  def set_drone
    #@drone = Drone.find(params[:id])
  end

  def drone_params
    params.require(:drone).permit(
    :name, 
    :introduction, 
    :price, 
    :area, 
    :maker_id, 
    :station_id, 
    :size_id, 
    :weight_id, 
    :load_id, 
    :space_id, 
    imgs_attributes: [:src, :_destroy, :id]
    ).merge(owner_id: current_user.id, status: 0)
  end
end

app/controllers/mypage_controller.rb
class MypageController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
    @user = User.find_by(id: current_user.id)
  end

  def update
    if current_user.update(user_params)
      redirect_to mypage_index
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:nickname, :email, :family_name, :first_name, :family_name_kana, :first_name_kana, :phone_number)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/drones/_drone_form.html.haml
.drone_new
  = form_for @drone, local: true do |f|
    .drone_input
      %label.drone_input__label
        画像の登録
        %span.required 必須
      %p.drone_input__text 最大5枚まで登録可能
      .drone_input__imgs
        = f.fields_for :imgs do |img|
          .up_group
            .preview
              //ここにプレビュー表示
            %label.img_input
              %p.img_message
                ドラッグ & ドロップ
                %br
                クリックでアップロード
              .img_input__tag
                = img.file_field :src, class:"img_input__tag__area", type: 'file', multiple: true, accept: "image/*"

    .drone_input
      %label.drone_input__label
        ドローン名
        %span.required 必須
        = f.text_field :name, class: "drone_input__label__text_form", id: "drone_name", placeholder: "30文字まで"
    .drone_input
      %label.drone_input__label
        詳細情報
        %span.required 必須
        = f.text_area :introduction, placeholder: "必須 1,000文字以内\r\n例）飛行安定性が高く、運送時の振動衝撃が少なめです。\r\n冷蔵機能を搭載しています。", rows: "7", class: "drone_input__text_area"
        .drone_input__label__words_count
          %span.countup 0 
          %span /1000
    .drone_input
      = f.fields_for :maker do |m|
        %label.drone_input__label
          メーカー情報
          %span.option 任意
        .pulldown#maker_select
          =m.text_field :name, class: "drone_input__label__text_form", placeholder: "メーカー情報"
        %label.drone_input__label
          タイプ
          %span.option 任意
        .pulldown#maker_select
          =m.text_field :type, class: "drone_input__label__text_form", placeholder: "型、機種など"
    .drone_input
      %label.drone_input__label
        大きさ
        %span.required 必須
      .pulldown#size_select
        =f.collection_select :size_id, Size.all, :id, :name, {include_blank: "選択してください"}, {class: "size_box"}
    .drone_input
      %label.drone_input__label
        重量
        %span.required 必須
      .pulldown#weight_select
        =f.collection_select :weight_id, Weight.all, :id, :name, {include_blank: "選択してください"}, {class: "weight_box"}
    .drone_input
      %label.drone_input__label
        飛行速度
        %span.required 必須
      .pulldown#speed_select
        =f.collection_select :speed_id, Speed.all, :id, :name, {include_blank: "選択してください"}, {class: "speed_box"}

    .drone_input
      %label.drone_input__label
        ステーション
        %span.required 必須
      .pulldown#parent_box
        = f.select :station, options_for_select( @station_parent_array.map{|c| [c[:name], c[:id]]}),{include_blank: "選択してください"}, { class: "parent_station_box", id: "parent_station"}
    .drone_input
      %label.drone_input__label
        飛行距離
        %span.required 必須
      .area_box.number_box
        =f.number_field :area, class: "area_box__form", min: 10, max: 9999999, placeholder: "0"
        %p.area_form
          km 以内
    .drone_input
      %label.drone_input__label
        荷物の大きさ制限
        %span.required 必須
      .pulldown#space_select
        =f.collection_select :space_id, Space.all, :id, :name, {include_blank: "選択してください"}, {class: "space_box"}
    .drone_input
      %label.drone_input__label
        荷物の重量制限
        %span.required 必須
      .pulldown#load_select
        =f.collection_select :load_id, Load.all, :id, :name, {include_blank: "選択してください"}, {class: "load_box"}
    .drone_input
      %label.drone_input__label
        単位時間あたりの価格
        %span.required 必須
      .price_box.number_box
        %p.price_form
          ¥
        =f.number_field :price, class: "price_box__form", min: 100, max: 9999999, placeholder: "0"
    .new_btn
      =f.submit "登録", class: "new_btn__post"
      =link_to "戻る", root_path, class:"new_btn__return"

app/views/drones/edit.html.haml
= render "layouts/header"
.edit_page
  編集ページ
= render "drone_form"
= render "layouts/footer"

app/views/drones/index.html.haml
.wrapper
  = render 'layouts/header'
  .drone_main
    .drone_main__text
      .tytle
        droneMail
      .message
        空のメッセンジャー
    .drone_main__index
      ドローン一覧
      .drone_main__index__box.drone_main__index__1st
        .drone_box
          .drone_box__img
            No Image
          .drone_box__station
            ステーション名
          .drone_box__coment
            ドローン名
        .drone_box
          .drone_box__img
            No Image
          .drone_box__station
            ステーション名
          .drone_box__coment
            ドローン名
        .drone_box
          .drone_box__img
            No Image
          .drone_box__station
            ステーション名
          .drone_box__coment
            ドローン名
        .drone_box
          .drone_box__img
            No Image
          .drone_box__station
            ステーション名
          .drone_box__coment
            ドローン名
      .drone_main__index__box.drone_main__index__2nd
        .drone_box
          .drone_box__img
            No Image
          .drone_box__station
            ステーション名
          .drone_box__coment
            ドローン名
        .drone_box
          .drone_box__img
            No Image
          .drone_box__station
            ステーション名
          .drone_box__coment
            ドローン名
        .drone_box
          .drone_box__img
            No Image
          .drone_box__station
            ステーション名
          .drone_box__coment
            ドローン名
        .drone_box
          .drone_box__img
            No Image
          .drone_box__station
            ステーション名
          .drone_box__coment
            ドローン名
  = render 'layouts/footer'

app/views/drones/new.html.haml
= render "layouts/header"
= render "drone_form"
= render "layouts/footer"

app/views/drones/request.html.haml
= render "layouts/header"
.request_page
  wsss
= render "layouts/footer"

app/views/drones/show.html.haml
= render "layouts/header"
.drone_show
  .drone_show__name
    ドローン名
  .drone_show__box
    .drone_show__box__imgs
      No Image
    .drone_show__box__content
      .drone_show__box__content__owner.block
        所有者
      .drone_show__box__content__station.block
        ステーション
      .drone_show__box__content__maker.block
        メーカー情報
      .drone_show__box__content__size.block
        大きさ、重量
      .drone_show__box__content__spec.block
        速度、距離
      .drone_show__box__content__postage.block
        重さ制限、大きさ制限
    .drone_show__box__content.real_data
      .drone_show__box__content__owner.block
        所有者
      .drone_show__box__content__station.block
        ステーション
      .drone_show__box__content__maker.block
        メーカー情報
      .drone_show__box__content__size.block
        大きさ、重量
      .drone_show__box__content__spec.block
        速度、距離
      .drone_show__box__content__postage.block
        重さ制限、大きさ制限
  .drone_show__price
    ¥ 100   円/時間  (税込)
  .drone_show__introduction
    詳細情報
  .btn
    =link_to "配達依頼に進む", root_path, class:"new_btn"
= render "layouts/footer"

app/views/layouts/_footer.html.haml
.footer
  @ droneMail. Inc.

app/views/layouts/_header.html.haml
.header
  .header__up
    .header__up__logo
      = link_to root_path, class: "tytle"  do
        droneMail
        = image_tag 'drone.jpg', size: "40x40", class: "header__up__logo__icon"
    .header__up__link
      = link_to new_drone_path, class: "link" do
        登録
      = link_to user_session_path, class: "link" do
        =icon("fa", "user")
        新規登録
      = link_to mypage_index_path, class: "link" do
        Mypage
  .header__serch
    = form_with url: '#' do |f|
      = f.text_field :search, placeholder: "キーワード入力", class: "header__serch__form"
      = button_tag type: "submit", class: "header__serch__btn" do
        = icon('fa', 'search fa-2x')

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title DroneMail
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/mypage/index.html.haml
= render "layouts/header"
.mypage
  .mypage__band
    = link_to mypage_index_path, class: "mypage__band__btn" do
      マイページ
    = link_to root_path, class: "mypage__band__btn" do
      ステーション検索
    = link_to root_path, class: "mypage__band__btn" do
      予約確認・変更
    = link_to root_path, class: "mypage__band__btn" do
      利用履歴
    = link_to root_path, class: "mypage__band__btn" do
      登録情報
  .content
    .side    
      .mypage__body
        .mypage__body__message
          2020年5月22日（金）
          .mypage__body__message__user
            ようこそ　
            .mypage__body__message__user__name
              ユーザー　
            %span さん
        .mypage__body__price
          直近の利用金額　2940 円
          .mypage__body__price__btn
            確認
        .mypage__body__tiket
          .mypage__body__tiket__title
            ドローンシェアeチケット
          .mypage__body__tiket__num
            .mypage__body__tiket__num__label
              保有枚数 
            .mypage__body__tiket__num__btn
              1枚
          .mypage__body__tiket__limit
            .mypage__body__tiket__limit__label
              有効期限最短
            .mypage__body__tiket__limit__date
              2020年07月14日
          #p
            ＞ドローンシェアeチケットとは何ですか？
    .mypage__request
      .mypage__request__favorite
        .mypage__request__favorite__title    
          お気に入りステーション
        .mypage__request__favorite__station
          ステーション名
          .mypage__request__favorite__station__btn
            送信
        #p
          ※各ステーション詳細ページの「お気に入りに追加」ボタンをクリックすると、お気に入りステーションに登録できます。
      .mypage__request__history
        .mypage__request__history__title
          予約ステーション履歴から選択
        .select
          .mypage__request__history__select
            選択肢
          .mypage__request__history__btn
            予約
= render "layouts/footer"

app/views/mypage/users/edit.html.haml
= render 'layouts/header'
.test
  テスト
= render 'layouts/footer'